// Legendary & Mythical Pokémon database, Gen 1-9.
const LEGENDARY_DEX = [
  // Gen 1
  { id: 144, name: "Articuno", gen: 1, category: "Legendary", types: ["Ice", "Flying"], ability: "Pressure", item: "Leftovers", nature: "Bold", moves: ["Freeze-Dry", "Roost", "Substitute", "Hurricane"], signature: null },
  { id: 145, name: "Zapdos", gen: 1, category: "Legendary", types: ["Electric", "Flying"], ability: "Static", item: "Heavy-Duty Boots", nature: "Timid", moves: ["Thunderbolt", "Hurricane", "Roost", "Volt Switch"], signature: null },
  { id: 146, name: "Moltres", gen: 1, category: "Legendary", types: ["Fire", "Flying"], ability: "Flame Body", item: "Heavy-Duty Boots", nature: "Timid", moves: ["Fire Blast", "Hurricane", "Roost", "U-turn"], signature: null },
  { id: 150, name: "Mewtwo", gen: 1, category: "Legendary", types: ["Psychic"], ability: "Pressure", item: "Life Orb", nature: "Timid", moves: ["Psystrike", "Ice Beam", "Aura Sphere", "Recover"], signature: "Psystrike" },
  { id: 151, name: "Mew", gen: 1, category: "Mythical", types: ["Psychic"], ability: "Synchronize", item: "Leftovers", nature: "Bold", moves: ["Psychic", "Roost", "Stealth Rock", "Will-O-Wisp"], signature: null },

  // Gen 2
  { id: 243, name: "Raikou", gen: 2, category: "Legendary", types: ["Electric"], ability: "Pressure", item: "Heavy-Duty Boots", nature: "Timid", moves: ["Thunderbolt", "Volt Switch", "Aura Sphere", "Calm Mind"], signature: null },
  { id: 244, name: "Entei", gen: 2, category: "Legendary", types: ["Fire"], ability: "Pressure", item: "Choice Band", nature: "Jolly", moves: ["Sacred Fire", "Extreme Speed", "Stone Edge", "Flare Blitz"], signature: "Sacred Fire" },
  { id: 245, name: "Suicune", gen: 2, category: "Legendary", types: ["Water"], ability: "Pressure", item: "Leftovers", nature: "Bold", moves: ["Scald", "Calm Mind", "Rest", "Sleep Talk"], signature: null },
  { id: 249, name: "Lugia", gen: 2, category: "Legendary", types: ["Psychic", "Flying"], ability: "Multiscale", item: "Leftovers", nature: "Bold", moves: ["Aeroblast", "Roost", "Toxic", "Calm Mind"], signature: "Aeroblast" },
  { id: 250, name: "Ho-Oh", gen: 2, category: "Legendary", types: ["Fire", "Flying"], ability: "Regenerator", item: "Heavy-Duty Boots", nature: "Adamant", moves: ["Sacred Fire", "Brave Bird", "Sacred Ash", "Recover"], signature: "Sacred Fire" },
  { id: 251, name: "Celebi", gen: 2, category: "Mythical", types: ["Psychic", "Grass"], ability: "Natural Cure", item: "Leftovers", nature: "Bold", moves: ["Giga Drain", "Nasty Plot", "Recover", "Psychic"], signature: null },

  // Gen 3
  { id: 377, name: "Regirock", gen: 3, category: "Legendary", types: ["Rock"], ability: "Sturdy", item: "Leftovers", nature: "Impish", moves: ["Stone Edge", "Body Press", "Curse", "Rest"], signature: null },
  { id: 378, name: "Regice", gen: 3, category: "Legendary", types: ["Ice"], ability: "Clear Body", item: "Leftovers", nature: "Bold", moves: ["Ice Beam", "Thunder Wave", "Toxic", "Rest"], signature: null },
  { id: 379, name: "Registeel", gen: 3, category: "Legendary", types: ["Steel"], ability: "Clear Body", item: "Leftovers", nature: "Impish", moves: ["Body Press", "Iron Head", "Curse", "Rest"], signature: null },
  { id: 380, name: "Latias", gen: 3, category: "Legendary", types: ["Dragon", "Psychic"], ability: "Levitate", item: "Soul Dew", nature: "Timid", moves: ["Draco Meteor", "Psyshock", "Recover", "Calm Mind"], signature: null },
  { id: 381, name: "Latios", gen: 3, category: "Legendary", types: ["Dragon", "Psychic"], ability: "Levitate", item: "Soul Dew", nature: "Timid", moves: ["Draco Meteor", "Psyshock", "Roost", "Defog"], signature: null },
  { id: 382, name: "Kyogre", gen: 3, category: "Legendary", types: ["Water"], ability: "Drizzle", item: "Choice Scarf", nature: "Modest", moves: ["Water Spout", "Origin Pulse", "Ice Beam", "Thunder"], signature: "Origin Pulse" },
  { id: 383, name: "Groudon", gen: 3, category: "Legendary", types: ["Ground"], ability: "Drought", item: "Assault Vest", nature: "Adamant", moves: ["Precipice Blades", "Stone Edge", "Swords Dance", "Fire Punch"], signature: "Precipice Blades" },
  { id: 384, name: "Rayquaza", gen: 3, category: "Legendary", types: ["Dragon", "Flying"], ability: "Air Lock", item: "Life Orb", nature: "Jolly", moves: ["Dragon Ascent", "Swords Dance", "Extreme Speed", "Earthquake"], signature: "Dragon Ascent" },
  { id: 385, name: "Jirachi", gen: 3, category: "Mythical", types: ["Steel", "Psychic"], ability: "Serene Grace", item: "Leftovers", nature: "Bold", moves: ["Iron Head", "Body Slam", "Wish", "Protect"], signature: null },
  { id: 386, name: "Deoxys", gen: 3, category: "Mythical", types: ["Psychic"], ability: "Pressure", item: "Life Orb", nature: "Naive", moves: ["Psycho Boost", "Superpower", "Ice Beam", "Extreme Speed"], signature: null },

  // Gen 4
  { id: 480, name: "Uxie", gen: 4, category: "Legendary", types: ["Psychic"], ability: "Levitate", item: "Leftovers", nature: "Bold", moves: ["Stealth Rock", "U-turn", "Knock Off", "Thunder Wave"], signature: null },
  { id: 481, name: "Mesprit", gen: 4, category: "Legendary", types: ["Psychic"], ability: "Levitate", item: "Leftovers", nature: "Bold", moves: ["Psychic", "U-turn", "Thunder Wave", "Healing Wish"], signature: null },
  { id: 482, name: "Azelf", gen: 4, category: "Legendary", types: ["Psychic"], ability: "Levitate", item: "Life Orb", nature: "Naive", moves: ["Psychic", "Fire Blast", "Explosion", "U-turn"], signature: null },
  { id: 483, name: "Dialga", gen: 4, category: "Legendary", types: ["Steel", "Dragon"], ability: "Pressure", item: "Adamant Orb", nature: "Modest", moves: ["Roar of Time", "Draco Meteor", "Flash Cannon", "Fire Blast"], signature: "Roar of Time" },
  { id: 484, name: "Palkia", gen: 4, category: "Legendary", types: ["Water", "Dragon"], ability: "Pressure", item: "Lustrous Orb", nature: "Modest", moves: ["Spacial Rend", "Hydro Pump", "Draco Meteor", "Fire Blast"], signature: "Spacial Rend" },
  { id: 485, name: "Heatran", gen: 4, category: "Legendary", types: ["Fire", "Steel"], ability: "Flash Fire", item: "Leftovers", nature: "Timid", moves: ["Magma Storm", "Earth Power", "Taunt", "Stealth Rock"], signature: null },
  { id: 486, name: "Regigigas", gen: 4, category: "Legendary", types: ["Normal"], ability: "Slow Start", item: "Leftovers", nature: "Adamant", moves: ["Crush Grip", "Knock Off", "Thunder Punch", "Drain Punch"], signature: "Crush Grip" },
  { id: 487, name: "Giratina", gen: 4, category: "Legendary", types: ["Ghost", "Dragon"], ability: "Levitate", item: "Griseous Orb", nature: "Bold", moves: ["Dragon Tail", "Will-O-Wisp", "Defog", "Rest"], signature: null },
  { id: 488, name: "Cresselia", gen: 4, category: "Legendary", types: ["Psychic"], ability: "Levitate", item: "Leftovers", nature: "Bold", moves: ["Moonlight", "Ice Beam", "Psyshock", "Toxic"], signature: null },
  { id: 490, name: "Manaphy", gen: 4, category: "Mythical", types: ["Water"], ability: "Hydration", item: "Leftovers", nature: "Bold", moves: ["Tail Glow", "Scald", "Ice Beam", "Rest"], signature: null },
  { id: 491, name: "Darkrai", gen: 4, category: "Mythical", types: ["Dark"], ability: "Bad Dreams", item: "Leftovers", nature: "Timid", moves: ["Dark Void", "Nasty Plot", "Dark Pulse", "Ice Beam"], signature: "Dark Void" },
  { id: 492, name: "Shaymin", gen: 4, category: "Mythical", types: ["Grass"], ability: "Natural Cure", item: "Leftovers", nature: "Timid", moves: ["Seed Flare", "Earth Power", "Air Slash", "Growth"], signature: "Seed Flare" },
  { id: 493, name: "Arceus", gen: 4, category: "Legendary", types: ["Normal"], ability: "Multitype", item: "Life Orb", nature: "Adamant", moves: ["Judgment", "Extreme Speed", "Swords Dance", "Recover"], signature: "Judgment" },

  // Gen 5
  { id: 494, name: "Victini", gen: 5, category: "Mythical", types: ["Psychic", "Fire"], ability: "Victory Star", item: "Choice Scarf", nature: "Jolly", moves: ["V-create", "Bolt Strike", "U-turn", "Zen Headbutt"], signature: "V-create" },
  { id: 638, name: "Cobalion", gen: 5, category: "Legendary", types: ["Steel", "Fighting"], ability: "Justified", item: "Leftovers", nature: "Jolly", moves: ["Close Combat", "Iron Head", "Stone Edge", "Swords Dance"], signature: null },
  { id: 639, name: "Terrakion", gen: 5, category: "Legendary", types: ["Rock", "Fighting"], ability: "Justified", item: "Choice Band", nature: "Jolly", moves: ["Close Combat", "Stone Edge", "Earthquake", "Quick Attack"], signature: null },
  { id: 640, name: "Virizion", gen: 5, category: "Legendary", types: ["Grass", "Fighting"], ability: "Justified", item: "Leftovers", nature: "Jolly", moves: ["Leaf Blade", "Close Combat", "Swords Dance", "Stone Edge"], signature: null },
  { id: 641, name: "Tornadus", gen: 5, category: "Legendary", types: ["Flying"], ability: "Prankster", item: "Heavy-Duty Boots", nature: "Timid", moves: ["Bleakwind Storm", "Hurricane", "Nasty Plot", "Taunt"], signature: null },
  { id: 642, name: "Thundurus", gen: 5, category: "Legendary", types: ["Electric", "Flying"], ability: "Prankster", item: "Life Orb", nature: "Timid", moves: ["Wildbolt Storm", "Sludge Wave", "Nasty Plot", "Thunder"], signature: null },
  { id: 643, name: "Reshiram", gen: 5, category: "Legendary", types: ["Dragon", "Fire"], ability: "Turboblaze", item: "Choice Specs", nature: "Timid", moves: ["Blue Flare", "Draco Meteor", "Earth Power", "Stone Edge"], signature: "Blue Flare" },
  { id: 644, name: "Zekrom", gen: 5, category: "Legendary", types: ["Dragon", "Electric"], ability: "Teravolt", item: "Choice Band", nature: "Adamant", moves: ["Bolt Strike", "Outrage", "Fusion Bolt", "Iron Head"], signature: "Bolt Strike" },
  { id: 645, name: "Landorus", gen: 5, category: "Legendary", types: ["Ground", "Flying"], ability: "Sheer Force", item: "Life Orb", nature: "Naive", moves: ["Earth Power", "Sludge Wave", "Focus Blast", "U-turn"], signature: null },
  { id: 646, name: "Kyurem", gen: 5, category: "Legendary", types: ["Dragon", "Ice"], ability: "Pressure", item: "Loaded Dice", nature: "Timid", moves: ["Freeze-Dry", "Ice Beam", "Earth Power", "Draco Meteor"], signature: null },
  { id: 647, name: "Keldeo", gen: 5, category: "Mythical", types: ["Water", "Fighting"], ability: "Justified", item: "Choice Specs", nature: "Timid", moves: ["Secret Sword", "Hydro Pump", "Icy Wind", "Scald"], signature: "Secret Sword" },
  { id: 648, name: "Meloetta", gen: 5, category: "Mythical", types: ["Normal", "Psychic"], ability: "Serene Grace", item: "Leftovers", nature: "Bold", moves: ["Relic Song", "Psychic", "Calm Mind", "Recover"], signature: "Relic Song" },
  { id: 649, name: "Genesect", gen: 5, category: "Mythical", types: ["Bug", "Steel"], ability: "Download", item: "Choice Scarf", nature: "Hasty", moves: ["Techno Blast", "Ice Beam", "Flamethrower", "U-turn"], signature: "Techno Blast" },

  // Gen 6
  { id: 716, name: "Xerneas", gen: 6, category: "Legendary", types: ["Fairy"], ability: "Fairy Aura", item: "Power Herb", nature: "Modest", moves: ["Geomancy", "Moonblast", "Focus Blast", "Thunder"], signature: "Geomancy" },
  { id: 717, name: "Yveltal", gen: 6, category: "Legendary", types: ["Dark", "Flying"], ability: "Dark Aura", item: "Life Orb", nature: "Timid", moves: ["Oblivion Wing", "Dark Pulse", "Focus Blast", "Roost"], signature: "Oblivion Wing" },
  { id: 718, name: "Zygarde", gen: 6, category: "Legendary", types: ["Dragon", "Ground"], ability: "Power Construct", item: "Leftovers", nature: "Careful", moves: ["Thousand Arrows", "Coil", "Substitute", "Dragon Tail"], signature: "Thousand Arrows" },
  { id: 719, name: "Diancie", gen: 6, category: "Mythical", types: ["Rock", "Fairy"], ability: "Clear Body", item: "Diancite", nature: "Timid", moves: ["Diamond Storm", "Moonblast", "Earth Power", "Protect"], signature: "Diamond Storm" },
  { id: 720, name: "Hoopa", gen: 6, category: "Mythical", types: ["Psychic", "Ghost"], ability: "Magician", item: "Life Orb", nature: "Timid", moves: ["Hyperspace Hole", "Nasty Plot", "Psychic", "Shadow Ball"], signature: "Hyperspace Hole" },
  { id: 721, name: "Volcanion", gen: 6, category: "Mythical", types: ["Fire", "Water"], ability: "Water Absorb", item: "Assault Vest", nature: "Modest", moves: ["Steam Eruption", "Sludge Bomb", "Earth Power", "Flamethrower"], signature: "Steam Eruption" },

  // Gen 7
  { id: 785, name: "Tapu Koko", gen: 7, category: "Legendary", types: ["Electric", "Fairy"], ability: "Electric Surge", item: "Life Orb", nature: "Naive", moves: ["Wild Charge", "U-turn", "Dazzling Gleam", "Nature's Madness"], signature: "Nature's Madness" },
  { id: 786, name: "Tapu Lele", gen: 7, category: "Legendary", types: ["Psychic", "Fairy"], ability: "Psychic Surge", item: "Choice Specs", nature: "Timid", moves: ["Psychic", "Moonblast", "Focus Blast", "Nature's Madness"], signature: "Nature's Madness" },
  { id: 787, name: "Tapu Bulu", gen: 7, category: "Legendary", types: ["Grass", "Fairy"], ability: "Grassy Surge", item: "Leftovers", nature: "Careful", moves: ["Horn Leech", "Zen Headbutt", "Synthesis", "Nature's Madness"], signature: "Nature's Madness" },
  { id: 788, name: "Tapu Fini", gen: 7, category: "Legendary", types: ["Water", "Fairy"], ability: "Misty Surge", item: "Leftovers", nature: "Calm", moves: ["Scald", "Moonblast", "Calm Mind", "Nature's Madness"], signature: "Nature's Madness" },
  { id: 791, name: "Solgaleo", gen: 7, category: "Legendary", types: ["Psychic", "Steel"], ability: "Full Metal Body", item: "Metronome", nature: "Adamant", moves: ["Sunsteel Strike", "Zen Headbutt", "Flare Blitz", "Iron Head"], signature: "Sunsteel Strike" },
  { id: 792, name: "Lunala", gen: 7, category: "Legendary", types: ["Psychic", "Ghost"], ability: "Shadow Shield", item: "Life Orb", nature: "Timid", moves: ["Moongeist Beam", "Calm Mind", "Moonblast", "Ice Beam"], signature: "Moongeist Beam" },
  { id: 800, name: "Necrozma", gen: 7, category: "Legendary", types: ["Psychic"], ability: "Prism Armor", item: "Ultranecrozium Z", nature: "Timid", moves: ["Photon Geyser", "Dragon Pulse", "Earth Power", "Calm Mind"], signature: "Photon Geyser" },
  { id: 801, name: "Magearna", gen: 7, category: "Mythical", types: ["Steel", "Fairy"], ability: "Soul-Heart", item: "Assault Vest", nature: "Modest", moves: ["Fleur Cannon", "Flash Cannon", "Focus Blast", "Volt Switch"], signature: "Fleur Cannon" },
  { id: 802, name: "Marshadow", gen: 7, category: "Mythical", types: ["Fighting", "Ghost"], ability: "Technician", item: "Life Orb", nature: "Jolly", moves: ["Spectral Thief", "Close Combat", "Ice Punch", "Swords Dance"], signature: "Spectral Thief" },
  { id: 807, name: "Zeraora", gen: 7, category: "Mythical", types: ["Electric"], ability: "Volt Absorb", item: "Life Orb", nature: "Jolly", moves: ["Plasma Fists", "Close Combat", "Knock Off", "U-turn"], signature: "Plasma Fists" },
  { id: 808, name: "Meltan", gen: 7, category: "Mythical", types: ["Steel"], ability: "Magnet Pull", item: "Eviolite", nature: "Careful", moves: ["Thunderbolt", "Flash Cannon", "Recover", "Body Press"], signature: null },
  { id: 809, name: "Melmetal", gen: 7, category: "Mythical", types: ["Steel"], ability: "Iron Fist", item: "Leftovers", nature: "Adamant", moves: ["Double Iron Bash", "Earthquake", "Thunder Punch", "Superpower"], signature: "Double Iron Bash" },

  // Gen 8
  { id: 888, name: "Zacian", gen: 8, category: "Legendary", types: ["Fairy"], ability: "Intrepid Sword", item: "Rusted Sword", nature: "Jolly", moves: ["Behemoth Blade", "Play Rough", "Close Combat", "Sacred Sword"], signature: "Behemoth Blade" },
  { id: 889, name: "Zamazenta", gen: 8, category: "Legendary", types: ["Fighting"], ability: "Dauntless Shield", item: "Rusted Shield", nature: "Impish", moves: ["Behemoth Bash", "Iron Head", "Wild Charge", "Crunch"], signature: "Behemoth Bash" },
  { id: 890, name: "Eternatus", gen: 8, category: "Legendary", types: ["Poison", "Dragon"], ability: "Pressure", item: "Life Orb", nature: "Timid", moves: ["Dynamax Cannon", "Sludge Bomb", "Flamethrower", "Recover"], signature: "Dynamax Cannon" },
  { id: 891, name: "Kubfu", gen: 8, category: "Legendary", types: ["Fighting"], ability: "Inner Focus", item: "Eviolite", nature: "Adamant", moves: ["Close Combat", "Rock Tomb", "Substitute", "Bulk Up"], signature: null },
  { id: 892, name: "Urshifu", gen: 8, category: "Legendary", types: ["Fighting", "Dark"], ability: "Unseen Fist", item: "Focus Sash", nature: "Jolly", moves: ["Wicked Blow", "Close Combat", "Sucker Punch", "U-turn"], signature: "Wicked Blow" },
  { id: 893, name: "Zarude", gen: 8, category: "Mythical", types: ["Dark", "Grass"], ability: "Leaf Guard", item: "Life Orb", nature: "Jolly", moves: ["U-turn", "Close Combat", "Power Whip", "Knock Off"], signature: null },
  { id: 894, name: "Regieleki", gen: 8, category: "Legendary", types: ["Electric"], ability: "Transistor", item: "Choice Scarf", nature: "Jolly", moves: ["Thunderbolt", "Volt Switch", "Explosion", "Rapid Spin"], signature: null },
  { id: 895, name: "Regidrago", gen: 8, category: "Legendary", types: ["Dragon"], ability: "Dragon's Maw", item: "Life Orb", nature: "Adamant", moves: ["Dragon Energy", "Draco Meteor", "Earthquake", "Body Slam"], signature: "Dragon Energy" },
  { id: 896, name: "Glastrier", gen: 8, category: "Legendary", types: ["Ice"], ability: "Chilling Neigh", item: "Leftovers", nature: "Adamant", moves: ["High Horsepower", "Icicle Crash", "Swords Dance", "Substitute"], signature: null },
  { id: 897, name: "Spectrier", gen: 8, category: "Legendary", types: ["Ghost"], ability: "Grim Neigh", item: "Choice Specs", nature: "Timid", moves: ["Shadow Ball", "Nasty Plot", "Draining Kiss", "Substitute"], signature: null },
  { id: 898, name: "Calyrex", gen: 8, category: "Legendary", types: ["Psychic", "Grass"], ability: "As One", item: "Leftovers", nature: "Timid", moves: ["Astral Barrage", "Glacial Lance", "Giga Drain", "Calm Mind"], signature: "Astral Barrage / Glacial Lance" },

  // Gen 9
  { id: 1001, name: "Wo-Chien", gen: 9, category: "Legendary", types: ["Dark", "Grass"], ability: "Tablets of Ruin", item: "Leftovers", nature: "Calm", moves: ["Ruination", "Giga Drain", "Knock Off", "Leech Seed"], signature: "Ruination" },
  { id: 1002, name: "Chien-Pao", gen: 9, category: "Legendary", types: ["Dark", "Ice"], ability: "Sword of Ruin", item: "Focus Sash", nature: "Jolly", moves: ["Ice Spinner", "Sucker Punch", "Sacred Sword", "Ruination"], signature: "Ruination" },
  { id: 1003, name: "Ting-Lu", gen: 9, category: "Legendary", types: ["Dark", "Ground"], ability: "Vessel of Ruin", item: "Leftovers", nature: "Careful", moves: ["Earthquake", "Ruination", "Stomping Tantrum", "Whirlwind"], signature: "Ruination" },
  { id: 1004, name: "Chi-Yu", gen: 9, category: "Legendary", types: ["Dark", "Fire"], ability: "Beads of Ruin", item: "Choice Specs", nature: "Timid", moves: ["Overheat", "Dark Pulse", "Ruination", "Snarl"], signature: "Ruination" },
  { id: 1007, name: "Koraidon", gen: 9, category: "Legendary", types: ["Fighting", "Dragon"], ability: "Orichalcum Pulse", item: "Life Orb", nature: "Jolly", moves: ["Collision Course", "Flame Charge", "Close Combat", "Dragon Claw"], signature: "Collision Course" },
  { id: 1008, name: "Miraidon", gen: 9, category: "Legendary", types: ["Electric", "Dragon"], ability: "Hadron Engine", item: "Choice Specs", nature: "Modest", moves: ["Electro Drift", "Draco Meteor", "Volt Switch", "Overheat"], signature: "Electro Drift" },
  { id: 1009, name: "Walking Wake", gen: 9, category: "Legendary", types: ["Water", "Dragon"], ability: "Protosynthesis", item: "Choice Specs", nature: "Modest", moves: ["Hydro Steam", "Draco Meteor", "Flamethrower", "Dragon Pulse"], signature: null },
  { id: 1010, name: "Iron Leaves", gen: 9, category: "Legendary", types: ["Grass", "Psychic"], ability: "Quark Drive", item: "Choice Band", nature: "Jolly", moves: ["Leaf Blade", "Close Combat", "Psyblade", "Swords Dance"], signature: null },
  { id: 1014, name: "Okidogi", gen: 9, category: "Legendary", types: ["Poison", "Fighting"], ability: "Toxic Chain", item: "Leftovers", nature: "Careful", moves: ["Gunk Shot", "Close Combat", "Knock Off", "Bulk Up"], signature: null },
  { id: 1015, name: "Munkidori", gen: 9, category: "Legendary", types: ["Poison", "Psychic"], ability: "Toxic Chain", item: "Focus Sash", nature: "Timid", moves: ["Psychic", "Sludge Bomb", "Nasty Plot", "Bitter Malice"], signature: "Bitter Malice" },
  { id: 1016, name: "Fezandipiti", gen: 9, category: "Legendary", types: ["Poison", "Fairy"], ability: "Toxic Chain", item: "Heavy-Duty Boots", nature: "Timid", moves: ["Dazzling Gleam", "Sludge Wave", "Roost", "U-turn"], signature: null },
  { id: 1017, name: "Ogerpon", gen: 9, category: "Legendary", types: ["Grass"], ability: "Defiant", item: "Various Masks", nature: "Jolly", moves: ["Ivy Cudgel", "Horn Leech", "Swords Dance", "Encore"], signature: "Ivy Cudgel" },
  { id: 1024, name: "Terapagos", gen: 9, category: "Legendary", types: ["Normal"], ability: "Tera Shift", item: "Leftovers", nature: "Bold", moves: ["Tera Starstorm", "Earth Power", "Calm Mind", "Recover"], signature: "Tera Starstorm" },
  { id: 1025, name: "Pecharunt", gen: 9, category: "Mythical", types: ["Poison", "Ghost"], ability: "Poison Puppeteer", item: "Leftovers", nature: "Bold", moves: ["Malignant Chain", "Parting Shot", "Recover", "Nasty Plot"], signature: "Malignant Chain" },
];
