// Type lookup for every move used in legendary-data.js, so the compact
// moveset grid can show a type tag without any extra network calls.
const MOVE_TYPES = {
  "Aeroblast":"Flying","Air Slash":"Flying","Astral Barrage":"Ghost","Aura Sphere":"Fighting",
  "Behemoth Bash":"Steel","Behemoth Blade":"Steel","Bitter Malice":"Ghost","Bleakwind Storm":"Flying",
  "Blue Flare":"Fire","Body Press":"Fighting","Body Slam":"Normal","Bolt Strike":"Electric",
  "Brave Bird":"Flying","Bulk Up":"Fighting","Calm Mind":"Psychic","Close Combat":"Fighting",
  "Coil":"Poison","Collision Course":"Fighting","Crunch":"Dark","Crush Grip":"Normal","Curse":"Ghost",
  "Dark Pulse":"Dark","Dark Void":"Dark","Dazzling Gleam":"Fairy","Defog":"Flying",
  "Diamond Storm":"Rock","Double Iron Bash":"Steel","Draco Meteor":"Dragon","Dragon Ascent":"Flying",
  "Dragon Claw":"Dragon","Dragon Energy":"Dragon","Dragon Pulse":"Dragon","Dragon Tail":"Dragon",
  "Drain Punch":"Fighting","Draining Kiss":"Fairy","Dynamax Cannon":"Dragon","Earth Power":"Ground",
  "Earthquake":"Ground","Electro Drift":"Electric","Encore":"Normal","Explosion":"Normal",
  "Extreme Speed":"Normal","Fire Blast":"Fire","Fire Punch":"Fire","Flame Charge":"Fire",
  "Flamethrower":"Fire","Flare Blitz":"Fire","Flash Cannon":"Steel","Fleur Cannon":"Fairy",
  "Focus Blast":"Fighting","Freeze-Dry":"Ice","Fusion Bolt":"Electric","Geomancy":"Fairy",
  "Giga Drain":"Grass","Glacial Lance":"Ice","Growth":"Normal","Gunk Shot":"Poison",
  "Healing Wish":"Psychic","High Horsepower":"Ground","Horn Leech":"Grass","Hurricane":"Flying",
  "Hydro Pump":"Water","Hydro Steam":"Water","Hyperspace Hole":"Psychic","Ice Beam":"Ice",
  "Ice Punch":"Ice","Ice Spinner":"Ice","Icicle Crash":"Ice","Icy Wind":"Ice","Iron Head":"Steel",
  "Ivy Cudgel":"Grass","Judgment":"Normal","Knock Off":"Dark","Leaf Blade":"Grass",
  "Leech Seed":"Grass","Magma Storm":"Fire","Malignant Chain":"Poison","Moonblast":"Fairy",
  "Moongeist Beam":"Ghost","Moonlight":"Fairy","Nasty Plot":"Dark","Nature's Madness":"Fairy",
  "Oblivion Wing":"Flying","Origin Pulse":"Water","Outrage":"Dragon","Overheat":"Fire",
  "Parting Shot":"Dark","Photon Geyser":"Psychic","Plasma Fists":"Electric","Play Rough":"Fairy",
  "Power Whip":"Grass","Precipice Blades":"Ground","Protect":"Normal","Psyblade":"Psychic",
  "Psychic":"Psychic","Psycho Boost":"Psychic","Psyshock":"Psychic","Psystrike":"Psychic",
  "Quick Attack":"Normal","Rapid Spin":"Normal","Recover":"Normal","Relic Song":"Normal",
  "Rest":"Psychic","Roar of Time":"Dragon","Rock Tomb":"Rock","Roost":"Flying","Ruination":"Dark",
  "Sacred Ash":"Normal","Sacred Fire":"Fire","Sacred Sword":"Fighting","Scald":"Water",
  "Secret Sword":"Fighting","Seed Flare":"Grass","Shadow Ball":"Ghost","Sleep Talk":"Normal",
  "Sludge Bomb":"Poison","Sludge Wave":"Poison","Snarl":"Dark","Spacial Rend":"Dragon",
  "Spectral Thief":"Ghost","Stealth Rock":"Rock","Steam Eruption":"Water","Stomping Tantrum":"Ground",
  "Stone Edge":"Rock","Substitute":"Normal","Sucker Punch":"Dark","Sunsteel Strike":"Steel",
  "Superpower":"Fighting","Swords Dance":"Normal","Synthesis":"Grass","Tail Glow":"Bug",
  "Taunt":"Dark","Techno Blast":"Normal","Tera Starstorm":"Normal","Thousand Arrows":"Ground",
  "Thunder Punch":"Electric","Thunder Wave":"Electric","Thunder":"Electric","Thunderbolt":"Electric",
  "Toxic":"Poison","U-turn":"Bug","V-create":"Fire","Volt Switch":"Electric","Water Spout":"Water",
  "Whirlwind":"Normal","Wicked Blow":"Dark","Wild Charge":"Electric","Wildbolt Storm":"Electric",
  "Will-O-Wisp":"Fire","Wish":"Normal","Zen Headbutt":"Psychic"
};
